services:
  - type: web
    name: vc-task-manager-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn vc_task_manager_backend.main:app --host 0.0.0.0 --port $PORT"
    healthCheckPath: "/"
    autoDeploy: true
